### ISSUE TITLE
Questions about the default setting of parameter "warmup_epoch"

### ISSUE THREAD

**Issue by XiangQiu42** [dayu11/Differentially-Private-Deep-Learning#1]
Dear dayu11,

In your code, the parameter "warmup_epoch" is -1 by default, and it seems that you did not assign a new value to this parameter in your experiment. 

However, if "warmup_epoch" is -1, it seems that at the train function: 

https://github.com/dayu11/Differentially-Private-Deep-Learning/blob/77096c8a225a0d654f1c06caefaf5a210f85622c/vision/RGP/cifar_train.py#L261-L263

This part of code  will never be executed. 

So, Is that correct or I am missing something?

**Comment by dayu11** [comment]
Yes, you are correct. By default, the code directly decomposes the weight matrix itself instead of the historical update.

It turns out that directly decomposing the weight matrix also works. This may because as the training progresses, the weight matrix itself contains enough information about the historical update, i.e., we do not need to subtract the weight at initialization from the current weight to get the historical update. Still, you can set warmup_epoch>1 to compute the historical update explicitly.
