### ISSUE TITLE
About standard deviation of Gaussian noise

### ISSUE THREAD

**Issue by DmsKinson** [dayu11/Differentially-Private-Deep-Learning#3]
Hi dayu11,
I'm appreciated that you open source the code of your brilliant work. I'm confused about the standard deviation of Gaussian noise in your implementation. In vanilla DP-SGD, the standard deviation equals to sigma, a.k.a. noise multiplier,  times clip threshold.
https://github.com/dayu11/Differentially-Private-Deep-Learning/blob/55eb9a1b75472895588d388de7567f012c9bc9ed/vision/GEP/main.py#L219-L221

I don't get the reason why you divide it by the batch size.
Is there some details I missed?

**Comment by dayu11** [comment]
Hi DmsKinson,

Thanks for the question. We divide the batchsize because the noise is added to the average of gradients instead of the sum of gradients. This can prevent numerical overflow when using half precision and the batchsize is large and (although in this code we use full precision). You can find the gradient averaging operations at [here](https://github.com/dayu11/Differentially-Private-Deep-Learning/blob/55eb9a1b75472895588d388de7567f012c9bc9ed/vision/GEP/models/basis_matching.py#L192).

**Comment by DmsKinson** [comment]
Thanks for you response. So does it mean that the sensitivity of the gradient is clip*batchisize?

**Comment by dayu11** [comment]
Without average, the sensitivity is exactly the clip as in the DP-SGD paper.  With average, the sensitivity is clip/batchsize.

**Comment by DmsKinson** [comment]
I see. Thanks for your answer.
